list.h File Reference
#include <stdlib.h>
Data Structures
struct Node
struct List
Typedefs
typedef long long List_El
typedef long long List_Iterator
typedef enum list_error_en List_error
Enumerations
enum list_error_en {
LIST_OK = 0,
LIST_ERROR = 1,
LIST_OVERFLOW = 2,
LIST_UNDERFLOW = 3,
LIST_WRONG_INDEX = 4,
LIST_WRONG_REALLOC = 5,
LIST_CYCLE = 6
 }
Functions
List_error ListConstruct (struct List *lst, size_t capacity)
List_error ListDestruct (struct List *lst)
List_error ListDump (struct List *lst)
List_error ListBoost (struct List *lst)
List_error ListShrinkToFit (struct List *lst)
List_Iterator ListPushBack (struct List *lst, List_El x)
List_Iterator ListPushFront (struct List *lst, List_El x)
List_error ListPopBack (struct List *lst)
List_error ListPopFront (struct List *lst)
size_t ListSize (struct List *lst)
char isListBoosted (struct List *lst)
List_Iterator GetIterator (struct List *lst, long long logic_number)
List_Iterator GetIterator_Value (struct List *lst, List_El x)
List_El ListGetValue (struct List *lst, List_Iterator iter)
List_Iterator ListBegin (struct List *lst)
List_Iterator ListEnd (struct List *lst)
List_Iterator IteratorIncrease (struct List *lst, List_Iterator iter)
List_Iterator IteratorDecrease (struct List *lst, List_Iterator iter)
List_Iterator ListInsertBefore (struct List *lst, List_El x, List_Iterator iter)
List_Iterator ListInsertAfter (struct List *lst, List_El x, List_Iterator iter)
List_error ListErase (struct List *lst, List_Iterator iter)
Data Structure Documentation
struct Node
Definition at line 13 of file list.h.
Data Fields
long long
next
long long
prev
List_El
value
struct List
Definition at line 20 of file list.h.
Data Fields
char
boost_mode
size_t
capacity
struct Node *
data
long long
free
long long
head
size_t
size
Typedef Documentation
List_El
typedef long long List_El
Definition at line 9 of file list.h.
List_error
typedef enum list_error_en List_error
List_Iterator
typedef long long List_Iterator
Definition at line 11 of file list.h.
Enumeration Type Documentation
list_error_en
enum list_error_en
Enumerator
LIST_OK
LIST_ERROR
LIST_OVERFLOW
LIST_UNDERFLOW
LIST_WRONG_INDEX
LIST_WRONG_REALLOC
LIST_CYCLE
Definition at line 30 of file list.h.
{
    LIST_OK = 0,
    LIST_ERROR = 1,
    LIST_OVERFLOW = 2,
    LIST_UNDERFLOW = 3,
    LIST_WRONG_INDEX = 4,
    LIST_WRONG_REALLOC = 5,
    LIST_CYCLE = 6
} List_error;
Function Documentation
GetIterator()
List_Iterator GetIterator (struct List * lst, long long logic_number)
Get iterator by index in list. Works for O(n) if list unboosted, and for O(1) of list boosted
Parameters
lst Pointer to list
logic_number Index in list which iterator need to find
Returns
Iterator by index
Definition at line 540 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (logic_number >= lst->size || logic_number < 0)
        return -1;
    
    if (lst->boost_mode == 1)
        return logic_number;
    
    List_Iterator iterator = lst->head;
    
    for (int i = 0; i < logic_number; i++)
        iterator = lst->data[iterator].next;
    
    return iterator;
}
References List::boost_mode, List::data, List::head, LIST_OK, ListVerify(), Node::next, and List::size.
GetIterator_Value()
List_Iterator GetIterator_Value (struct List * lst, List_El x)
Get iterator by value of element. Finds first entry in list. If there's no element x returns -1
Parameters
lst Pointer to list
x Value what need to find
Returns
Iterator of the element, or -1 if there's no such value
Definition at line 561 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    List_Iterator iterator = -1;
    
    List_Iterator curr_node = lst->head;
    
    do{
        if (lst->data[curr_node].value == x)
        {
            iterator = curr_node;
            break;
        }
        curr_node = lst->data[curr_node].next;
    } while(curr_node != lst->head);
    
    return iterator;
}
References List::data, List::head, LIST_OK, ListVerify(), Node::next, and Node::value.
isListBoosted()
char isListBoosted (struct List * lst)
Check list's boost mode
Parameters
lst Pointer to list
Returns
1 if list boosted, 0 if it's not
Definition at line 530 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->boost_mode;
}
References List::boost_mode, LIST_OK, and ListVerify().
IteratorDecrease()
List_Iterator IteratorDecrease (struct List * lst, List_Iterator iter)
Get previous iterator by present iterator
Parameters
lst Pointer to list
iter Present iterator
Returns
Previoust iterator
Definition at line 630 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
        
    if (isIteratorValid(lst, iter))
        return lst->data[iter].prev;
    else
        return -1;
}
References List::data, isIteratorValid(), LIST_OK, ListVerify(), and Node::prev.
IteratorIncrease()
List_Iterator IteratorIncrease (struct List * lst, List_Iterator iter)
Get next iterator by present iterator
Parameters
lst Pointer to list
iter Present iterator
Returns
Next iterator
Definition at line 617 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (isIteratorValid(lst, iter))
        return lst->data[iter].next;
    else
        return -1;
}
References List::data, isIteratorValid(), LIST_OK, ListVerify(), and Node::next.
ListBegin()
List_Iterator ListBegin (struct List * lst)
Get iterator of the first element
Parameters
lst Pointer to list
Returns
Iterator of the first element
Definition at line 597 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->head;
}
References List::head, LIST_OK, and ListVerify().
ListBoost()
List_error ListBoost (struct List * lst)
Boosting list. Access from GetIterator will be by O(1). Boost mode turns off if you insert/erase element not in the end of the list. Works for O(n)
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 391 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->boost_mode == 1)
        return LIST_OK;
    
    if (lst->size == 0)
    {
        lst->boost_mode = 1;
        return LIST_OK;
    }
    
    struct Node *new_data = (struct Node *)calloc(lst->size, sizeof(struct Node));
    
    if (new_data == NULL)
        return LIST_WRONG_REALLOC;
    
    int curr_node = lst->head;
    for (int i = 0; i < lst->size; i++)
    {
        new_data[i].value = lst->data[curr_node].value;
        new_data[i].next = (i + 1) % lst->size;
        new_data[i].prev = (i - 1 + lst->size) % lst->size;
        curr_node = lst->data[curr_node].next;
    }
    
    free(lst->data);
    lst->data = new_data;
    lst->capacity = lst->size;
    lst->free = -1;
    lst->head = 0;
    lst->boost_mode = 1;
        
    return LIST_OK;
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_ERROR, LIST_OK, LIST_WRONG_REALLOC, ListVerify(), Node::next, Node::prev, List::size, and Node::value.
ListConstruct()
List_error ListConstruct (struct List * lst, size_t capacity)
Construct list structure
Parameters
lst Pointer to list
capacity Capacity of the list in the begining
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 275 of file list.c.
{
    assert(lst != NULL);
    
    if (capacity <= 0)
        capacity = 1;
    
    lst->data = (struct Node *)calloc(capacity, sizeof(struct Node));
    
    assert(lst->data != NULL);
    
    lst->free = 0;
    for (int i = 0; i < capacity - 1; i++)
    {
        struct Node free_node = {-1, -1, i + 1};
        lst->data[i] = free_node;
    }
    struct Node last_node = {-1, -1 , -1};
    lst->data[capacity - 1] = last_node;
    
    lst->head = -1;
    lst->capacity = capacity;
    lst->size = 0;
    lst->boost_mode = 0;
    
    return ListVerify(lst);
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, ListVerify(), and List::size.
ListDestruct()
List_error ListDestruct (struct List * lst)
Destruct list structure
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 303 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    free(lst->data);
    lst->capacity = 0;
    lst->size = 0;
    lst->head = -1;
    lst->free = -1;
    lst->boost_mode = 0;
    
    return ListVerify(lst);
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_ERROR, LIST_OK, ListVerify(), and List::size.
ListDump()
List_error ListDump (struct List * lst)
Function of dumping list. Creates ListDump.log and ListDump.pdf
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 320 of file list.c.
{
    assert(lst != NULL);
    
    FILE *dump = fopen("ListDump.log", "wb");
    fprintf(dump, "================== LIST DUMP ==================\n"
            "Size = %i\n"
            "Capacity = %i\n"
            "Head = %i\n"
            "Free = %i\n"
            "Boost Mode = %i\n",
            lst->size, lst->capacity, lst->head, lst->free, lst->boost_mode);
    fprintf(dump, "\nDATA:\n"
                      "№ | value | next | prev |\n");
    for (int i = 0; i < lst->capacity; i++)
    {
        fprintf(dump, "[%2i] |%14lli | %2i | %2i |\n", i, lst->data[i].value, lst->data[i].next, lst->data[i].prev);
    }
    fprintf(dump, "================== THE END ====================\n");
    
    fclose(dump);
    
    FILE *graph = fopen("graph.gv", "wb");
    
    fprintf(graph, "digraph structs {\n"
                   " node [shape=record];\n");
    
    const char * color = NULL;
    for (int i = 0; i < lst->capacity; i++)
    {
        if (lst->data[i].prev != -1)
            color = "#6659E1";
        else
            color = "#1CAC1C";
        
        fprintf(graph," struct_%i [shape=record, style = filled, fillcolor = \"%s\", "
                      "label=\" value = %i | number_array = %i |"
                      " {prev = %i | next = %i} \"];\n",
                      i, color, lst->data[i].value, i, lst->data[i].prev, lst->data[i].next);
    }
    
    if (lst->size >= 1)
    {
        fprintf(graph, "struct_%i [style = filled, fillcolor = \"#E5EF5A\"];\n", lst->head);
        if (lst->size >= 2)
            fprintf(graph, "struct_%i [style = filled, fillcolor = \"#FF353C\"];\n", lst->data[lst->head].prev);
    }
    
    for (int i = 0; i < lst->capacity; i++)
    {
        if (lst->data[i].prev == -1)
        {
            if (lst->data[i].next != -1)
                fprintf(graph, "struct_%i -> struct_%i;\n", i, lst->data[i].next);
        }
        else
        {
            fprintf(graph, "struct_%i -> struct_%i;\n", i, lst->data[i].next);
            fprintf(graph, "struct_%i -> struct_%i;\n", i, lst->data[i].prev);
        }
    }
    
    fprintf(graph, "}\n");
    
    fclose(graph);
    
    system("circo -Tpdf graph.gv -o ListDump.pdf && rm graph.gv");
    
    return LIST_OK;
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_OK, Node::next, Node::prev, List::size, and Node::value.
Referenced by isIteratorValid(), and ListVerify().
ListEnd()
List_Iterator ListEnd (struct List * lst)
Get iterator of the last element
Parameters
lst Pointer to list
Returns
Iterator of the last element
Definition at line 607 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->data[lst->head].prev;
}
References List::data, List::head, LIST_OK, ListVerify(), and Node::prev.
ListErase()
List_error ListErase (struct List * lst, List_Iterator iter)
Erase element by iterator
Parameters
lst Pointer to list
iter Iterator which element need to erase (iterator after that is wrong)
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 679 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (!isIteratorValid(lst, iter))
        return LIST_ERROR;
    if (iter == lst->data[lst->head].prev)
        return ListPopBack(lst);
        
    lst->boost_mode = 0;
    
    if (iter == lst->head)
        return ListPopFront(lst);
    
    return ListErase_Internal(lst, iter);
}
References List::boost_mode, List::data, List::head, isIteratorValid(), LIST_ERROR, LIST_OK, ListErase_Internal(), ListPopBack(), ListPopFront(), ListVerify(), and Node::prev.
ListGetValue()
List_El ListGetValue (struct List * lst, List_Iterator iter)
Get value of element in list by iterator
Parameters
lst Pointer to list
iter Iterator in list
Returns
Value of the element or -1 if there's something wrong
Definition at line 584 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
        
    if (isIteratorValid(lst, iter))
        return lst->data[iter].value;
    else
        return -1;
}
References List::data, isIteratorValid(), LIST_OK, ListVerify(), and Node::value.
ListInsertAfter()
List_Iterator ListInsertAfter (struct List * lst, List_El x, List_Iterator iter)
Insert element x after iterator
Parameters
lst Pointer to list
x Element which need to insert
iter Iterator after which need to insert element
Returns
Iterator of new inserted element
Definition at line 662 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (!isIteratorValid(lst, iter))
        return -1;
        
    if (iter == lst->data[lst->head].prev)
        return ListPushBack(lst, x);
    
    ListInsert_Internal(lst, x, lst->data[iter].next);
    return lst->data[iter].next;
}
References List::data, List::head, isIteratorValid(), LIST_OK, ListInsert_Internal(), ListPushBack(), ListVerify(), Node::next, and Node::prev.
ListInsertBefore()
List_Iterator ListInsertBefore (struct List * lst, List_El x, List_Iterator iter)
Insert element x before iterator.
Parameters
lst Pointer to list
x Element which need to insert
iter Iterator before which need to insert element
Returns
Iterator of new inserted element
Definition at line 643 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (!isIteratorValid(lst, iter))
        return -1;
    
    lst->boost_mode = 0;
    
    if (iter == lst->head)
        return ListPushFront(lst, x);
    
    ListInsert_Internal(lst, x, iter);
    return lst->data[iter].prev;
}
References List::boost_mode, List::data, List::head, isIteratorValid(), LIST_OK, ListInsert_Internal(), ListPushFront(), ListVerify(), and Node::prev.
ListPopBack()
List_error ListPopBack (struct List * lst)
Erase element in the end of the list
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 492 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->size == 0)
        return LIST_ERROR;
    
    return ListErase_Internal(lst, lst->data[lst->head].prev);
}
References List::data, List::head, LIST_ERROR, LIST_OK, ListErase_Internal(), ListVerify(), Node::prev, and List::size.
Referenced by ListErase().
ListPopFront()
List_error ListPopFront (struct List * lst)
Erase element in front of the list
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 505 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->size == 0)
        return LIST_ERROR;
    
    if (lst->boost_mode == 1) lst->boost_mode = 0;
    
    return ListErase_Internal(lst, lst->head);
}
References List::boost_mode, List::head, LIST_ERROR, LIST_OK, ListErase_Internal(), ListVerify(), and List::size.
Referenced by ListErase().
ListPushBack()
List_Iterator ListPushBack (struct List * lst, List_El x)
Insert element in the end of the list
Parameters
lst Pointer to list
x Element which need to insert in the end
Returns
Iterator of the element x in list
Definition at line 444 of file list.c.
{
    assert(lst != NULL);
        
    if (ListVerify(lst) != LIST_OK)
        return -1;
            
    if (lst->size > 0)
    {
        if (ListInsert_Internal(lst, x, lst->head) == LIST_OK)
            return lst->data[lst->head].prev;
        else
            return -1;
    }
    else
    {
        if (ListInsert_Internal(lst, x, 0) == LIST_OK)
            return lst->head;
        else
            return -1;
    }
}
References List::data, List::head, LIST_OK, ListInsert_Internal(), ListVerify(), Node::prev, and List::size.
Referenced by ListInsertAfter().
ListPushFront()
List_Iterator ListPushFront (struct List * lst, List_El x)
Insert element in the begin of the list
Parameters
lst Pointer to list
x Element which need to insert in the begin
Returns
Iterator of the element x in list
Definition at line 467 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    List_error check = LIST_OK;
    if (lst->boost_mode == 1) lst->boost_mode = 0;
    
    if (lst->size > 0)
        check = ListInsert_Internal(lst, x, lst->head);
    else
        check = ListInsert_Internal(lst, x, 0);
    
    if (check == LIST_OK)
    {
        lst->head = lst->data[lst->head].prev;
        return lst->head;
    }
    else
        return -1;
}
References List::boost_mode, List::data, List::head, LIST_OK, ListInsert_Internal(), ListVerify(), Node::prev, and List::size.
Referenced by ListInsertBefore().
ListShrinkToFit()
List_error ListShrinkToFit (struct List * lst)
Changes capacity to size. Works ONLY in boosted list
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 431 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->boost_mode == 1)
        return ListResize(lst, lst->size);
    else
        return LIST_ERROR;
}
References List::boost_mode, LIST_ERROR, LIST_OK, ListResize(), ListVerify(), and List::size.
ListSize()
size_t ListSize (struct List * lst)
Check list's size
Parameters
lst Pointer to list
Returns
Size of the list
Definition at line 520 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->size;
}
References LIST_OK, ListVerify(), and List::size.