list.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include `list.h`
Macros
#define DEBUG_MODE
Functions
static List_error ListVerify (struct List *lst)
static List_error ListResize (struct List *lst, size_t new_cap)
static List_error ListInsert_Internal (struct List *lst, List_El x, long long array_number)
static List_error ListErase_Internal (struct List *lst, long long array_number)
static char isIteratorValid (struct List *lst, List_Iterator iter)
List_error ListConstruct (struct List *lst, size_t capacity)
List_error ListDestruct (struct List *lst)
List_error ListDump (struct List *lst)
List_error ListBoost (struct List *lst)
List_error ListShrinkToFit (struct List *lst)
List_Iterator ListPushBack (struct List *lst, List_El x)
List_Iterator ListPushFront (struct List *lst, List_El x)
List_error ListPopBack (struct List *lst)
List_error ListPopFront (struct List *lst)
size_t ListSize (struct List *lst)
char isListBoosted (struct List *lst)
List_Iterator GetIterator (struct List *lst, long long logic_number)
List_Iterator GetIterator_Value (struct List *lst, List_El x)
List_El ListGetValue (struct List *lst, List_Iterator iter)
List_Iterator ListBegin (struct List *lst)
List_Iterator ListEnd (struct List *lst)
List_Iterator IteratorIncrease (struct List *lst, List_Iterator iter)
List_Iterator IteratorDecrease (struct List *lst, List_Iterator iter)
List_Iterator ListInsertBefore (struct List *lst, List_El x, List_Iterator iter)
List_Iterator ListInsertAfter (struct List *lst, List_El x, List_Iterator iter)
List_error ListErase (struct List *lst, List_Iterator iter)
Macro Definition Documentation
DEBUG_MODE
#define DEBUG_MODE
Definition at line 56 of file list.c.
Function Documentation
GetIterator()
List_Iterator GetIterator (struct List * lst, long long logic_number)
Get iterator by index in list. Works for O(n) if list unboosted, and for O(1) of list boosted
Parameters
lst Pointer to list
logic_number Index in list which iterator need to find
Returns
Iterator by index
Definition at line 540 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (logic_number >= lst->size || logic_number < 0)
        return -1;
    
    if (lst->boost_mode == 1)
        return logic_number;
    
    List_Iterator iterator = lst->head;
    
    for (int i = 0; i < logic_number; i++)
        iterator = lst->data[iterator].next;
    
    return iterator;
}
References List::boost_mode, List::data, List::head, LIST_OK, ListVerify(), Node::next, and List::size.
GetIterator_Value()
List_Iterator GetIterator_Value (struct List * lst, List_El x)
Get iterator by value of element. Finds first entry in list. If there's no element x returns -1
Parameters
lst Pointer to list
x Value what need to find
Returns
Iterator of the element, or -1 if there's no such value
Definition at line 561 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    List_Iterator iterator = -1;
    
    List_Iterator curr_node = lst->head;
    
    do{
        if (lst->data[curr_node].value == x)
        {
            iterator = curr_node;
            break;
        }
        curr_node = lst->data[curr_node].next;
    } while(curr_node != lst->head);
    
    return iterator;
}
References List::data, List::head, LIST_OK, ListVerify(), Node::next, and Node::value.
isIteratorValid()
static char isIteratorValid (struct List * lst, List_Iterator iter) [static]
Checking validity of iterator
Parameters
lst List where need to check iterator
iter Iterator in list which need to check
Returns
1 if iterator valid, or 0 if it's not
Definition at line 126 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return 0;
    
    if (iter < 0 || iter >= lst->capacity || lst->data[iter].prev == -1)
    {
        printf("Wrong iterator\n");
        ListDump(lst);
        return 0;
    }
    else
        return 1;
}
References List::capacity, List::data, LIST_OK, ListDump(), ListVerify(), and Node::prev.
Referenced by IteratorDecrease(), IteratorIncrease(), ListErase(), ListGetValue(), ListInsertAfter(), and ListInsertBefore().
isListBoosted()
char isListBoosted (struct List * lst)
Check list's boost mode
Parameters
lst Pointer to list
Returns
1 if list boosted, 0 if it's not
Definition at line 530 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->boost_mode;
}
References List::boost_mode, LIST_OK, and ListVerify().
IteratorDecrease()
List_Iterator IteratorDecrease (struct List * lst, List_Iterator iter)
Get previous iterator by present iterator
Parameters
lst Pointer to list
iter Present iterator
Returns
Previoust iterator
Definition at line 630 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
        
    if (isIteratorValid(lst, iter))
        return lst->data[iter].prev;
    else
        return -1;
}
References List::data, isIteratorValid(), LIST_OK, ListVerify(), and Node::prev.
IteratorIncrease()
List_Iterator IteratorIncrease (struct List * lst, List_Iterator iter)
Get next iterator by present iterator
Parameters
lst Pointer to list
iter Present iterator
Returns
Next iterator
Definition at line 617 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (isIteratorValid(lst, iter))
        return lst->data[iter].next;
    else
        return -1;
}
References List::data, isIteratorValid(), LIST_OK, ListVerify(), and Node::next.
ListBegin()
List_Iterator ListBegin (struct List * lst)
Get iterator of the first element
Parameters
lst Pointer to list
Returns
Iterator of the first element
Definition at line 597 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->head;
}
References List::head, LIST_OK, and ListVerify().
ListBoost()
List_error ListBoost (struct List * lst)
Boosting list. Access from GetIterator will be by O(1). Boost mode turns off if you insert/erase element not in the end of the list. Works for O(n)
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 391 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->boost_mode == 1)
        return LIST_OK;
    
    if (lst->size == 0)
    {
        lst->boost_mode = 1;
        return LIST_OK;
    }
    
    struct Node *new_data = (struct Node *)calloc(lst->size, sizeof(struct Node));
    
    if (new_data == NULL)
        return LIST_WRONG_REALLOC;
    
    int curr_node = lst->head;
    for (int i = 0; i < lst->size; i++)
    {
        new_data[i].value = lst->data[curr_node].value;
        new_data[i].next = (i + 1) % lst->size;
        new_data[i].prev = (i - 1 + lst->size) % lst->size;
        curr_node = lst->data[curr_node].next;
    }
    
    free(lst->data);
    lst->data = new_data;
    lst->capacity = lst->size;
    lst->free = -1;
    lst->head = 0;
    lst->boost_mode = 1;
        
    return LIST_OK;
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_ERROR, LIST_OK, LIST_WRONG_REALLOC, ListVerify(), Node::next, Node::prev, List::size, and Node::value.
ListConstruct()
List_error ListConstruct (struct List * lst, size_t capacity)
Construct list structure
Parameters
lst Pointer to list
capacity Capacity of the list in the begining
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 275 of file list.c.
{
    assert(lst != NULL);
    
    if (capacity <= 0)
        capacity = 1;
    
    lst->data = (struct Node *)calloc(capacity, sizeof(struct Node));
    
    assert(lst->data != NULL);
    
    lst->free = 0;
    for (int i = 0; i < capacity - 1; i++)
    {
        struct Node free_node = {-1, -1, i + 1};
        lst->data[i] = free_node;
    }
    struct Node last_node = {-1, -1 , -1};
    lst->data[capacity - 1] = last_node;
    
    lst->head = -1;
    lst->capacity = capacity;
    lst->size = 0;
    lst->boost_mode = 0;
    
    return ListVerify(lst);
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, ListVerify(), and List::size.
ListDestruct()
List_error ListDestruct (struct List * lst)
Destruct list structure
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 303 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    free(lst->data);
    lst->capacity = 0;
    lst->size = 0;
    lst->head = -1;
    lst->free = -1;
    lst->boost_mode = 0;
    
    return ListVerify(lst);
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_ERROR, LIST_OK, ListVerify(), and List::size.
ListDump()
List_error ListDump (struct List * lst)
Function of dumping list. Creates ListDump.log and ListDump.pdf
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 320 of file list.c.
{
    assert(lst != NULL);
    
    FILE *dump = fopen("ListDump.log", "wb");
    fprintf(dump, "================== LIST DUMP ==================\n"
            "Size = %i\n"
            "Capacity = %i\n"
            "Head = %i\n"
            "Free = %i\n"
            "Boost Mode = %i\n",
            lst->size, lst->capacity, lst->head, lst->free, lst->boost_mode);
    fprintf(dump, "\nDATA:\n"
                      "№ | value | next | prev |\n");
    for (int i = 0; i < lst->capacity; i++)
    {
        fprintf(dump, "[%2i] |%14lli | %2i | %2i |\n", i, lst->data[i].value, lst->data[i].next, lst->data[i].prev);
    }
    fprintf(dump, "================== THE END ====================\n");
    
    fclose(dump);
    
    FILE *graph = fopen("graph.gv", "wb");
    
    fprintf(graph, "digraph structs {\n"
                   " node [shape=record];\n");
    
    const char * color = NULL;
    for (int i = 0; i < lst->capacity; i++)
    {
        if (lst->data[i].prev != -1)
            color = "#6659E1";
        else
            color = "#1CAC1C";
        
        fprintf(graph," struct_%i [shape=record, style = filled, fillcolor = \"%s\", "
                      "label=\" value = %i | number_array = %i |"
                      " {prev = %i | next = %i} \"];\n",
                      i, color, lst->data[i].value, i, lst->data[i].prev, lst->data[i].next);
    }
    
    if (lst->size >= 1)
    {
        fprintf(graph, "struct_%i [style = filled, fillcolor = \"#E5EF5A\"];\n", lst->head);
        if (lst->size >= 2)
            fprintf(graph, "struct_%i [style = filled, fillcolor = \"#FF353C\"];\n", lst->data[lst->head].prev);
    }
    
    for (int i = 0; i < lst->capacity; i++)
    {
        if (lst->data[i].prev == -1)
        {
            if (lst->data[i].next != -1)
                fprintf(graph, "struct_%i -> struct_%i;\n", i, lst->data[i].next);
        }
        else
        {
            fprintf(graph, "struct_%i -> struct_%i;\n", i, lst->data[i].next);
            fprintf(graph, "struct_%i -> struct_%i;\n", i, lst->data[i].prev);
        }
    }
    
    fprintf(graph, "}\n");
    
    fclose(graph);
    
    system("circo -Tpdf graph.gv -o ListDump.pdf && rm graph.gv");
    
    return LIST_OK;
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_OK, Node::next, Node::prev, List::size, and Node::value.
Referenced by isIteratorValid(), and ListVerify().
ListEnd()
List_Iterator ListEnd (struct List * lst)
Get iterator of the last element
Parameters
lst Pointer to list
Returns
Iterator of the last element
Definition at line 607 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->data[lst->head].prev;
}
References List::data, List::head, LIST_OK, ListVerify(), and Node::prev.
ListErase()
List_error ListErase (struct List * lst, List_Iterator iter)
Erase element by iterator
Parameters
lst Pointer to list
iter Iterator which element need to erase (iterator after that is wrong)
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 679 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (!isIteratorValid(lst, iter))
        return LIST_ERROR;
    if (iter == lst->data[lst->head].prev)
        return ListPopBack(lst);
        
    lst->boost_mode = 0;
    
    if (iter == lst->head)
        return ListPopFront(lst);
    
    return ListErase_Internal(lst, iter);
}
References List::boost_mode, List::data, List::head, isIteratorValid(), LIST_ERROR, LIST_OK, ListErase_Internal(), ListPopBack(), ListPopFront(), ListVerify(), and Node::prev.
ListErase_Internal()
static List_error ListErase_Internal (struct List * lst, long long array_number) [static]
Erase element by array_number.
Parameters
lst List where need to erase element
array_number Number in array(iterator actually) which need to erase
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 233 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (array_number < 0 || array_number >= lst->capacity)
        return LIST_ERROR;
    
    if (lst->data[array_number].prev == -1)
        return LIST_ERROR;
    
    if (lst->size == 1)
    {
        lst->head = -1;
        
        struct Node dead_node = {-1, -1, lst->free};
        lst->data[array_number] = dead_node;
        lst->free = array_number;
        
        lst->size--;
        lst->boost_mode = 0;
        
        return LIST_OK;
    }
    
    if (lst->head == array_number)
        lst->head = lst->data[array_number].next;
    
    lst->data[lst->data[array_number].prev].next = lst->data[array_number].next;
    lst->data[lst->data[array_number].next].prev = lst->data[array_number].prev;
    
    struct Node dead_node = {-1, -1, lst->free};
    lst->data[array_number] = dead_node;
    lst->free = array_number;
    
    lst->size--;
    
    return LIST_OK;
}
References List::boost_mode, List::capacity, List::data, List::free, List::head, LIST_ERROR, LIST_OK, ListVerify(), Node::next, Node::prev, and List::size.
Referenced by ListErase(), ListPopBack(), and ListPopFront().
ListGetValue()
List_El ListGetValue (struct List * lst, List_Iterator iter)
Get value of element in list by iterator
Parameters
lst Pointer to list
iter Iterator in list
Returns
Value of the element or -1 if there's something wrong
Definition at line 584 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
        
    if (isIteratorValid(lst, iter))
        return lst->data[iter].value;
    else
        return -1;
}
References List::data, isIteratorValid(), LIST_OK, ListVerify(), and Node::value.
ListInsert_Internal()
static List_error ListInsert_Internal (struct List * lst, List_El x, long long array_number) [static]
Insert new element before array_number element. if array_number is head of the list insert new element in the end
Parameters
lst List where need to insert element
x Element of list which need to insert
array_number Number in array (iterator actually) before which need to insert element
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 190 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (array_number < 0 || array_number >= lst->capacity)
        return LIST_WRONG_INDEX;
    
    if (lst->data[array_number].prev == -1 && !(lst->size == 0 && array_number == 0))
        return LIST_WRONG_INDEX;
    
    if (lst->capacity == lst->size)
    {
        if (ListResize(lst, lst->capacity * 2) != LIST_OK)
            return LIST_WRONG_REALLOC;
    }
    
    int free_tmp = lst->free;
    lst->free = lst->data[free_tmp].next;
    
    if (lst->size == 0)
    {
        lst->head = free_tmp;
        struct Node new_node = {x, lst->head, lst->head};
        lst->data[lst->head] = new_node;
        
        lst->size++;
        return LIST_OK;
    }
    
    struct Node new_node = {x, lst->data[array_number].prev, array_number};
    
    lst->data[free_tmp] = new_node;
    lst->data[new_node.prev].next = free_tmp;
    lst->data[new_node.next].prev = free_tmp;
        
    lst->size++;
    
    return LIST_OK;
}
References List::capacity, List::data, List::free, List::head, LIST_ERROR, LIST_OK, LIST_WRONG_INDEX, LIST_WRONG_REALLOC, ListResize(), ListVerify(), Node::next, Node::prev, and List::size.
Referenced by ListInsertAfter(), ListInsertBefore(), ListPushBack(), and ListPushFront().
ListInsertAfter()
List_Iterator ListInsertAfter (struct List * lst, List_El x, List_Iterator iter)
Insert element x after iterator
Parameters
lst Pointer to list
x Element which need to insert
iter Iterator after which need to insert element
Returns
Iterator of new inserted element
Definition at line 662 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (!isIteratorValid(lst, iter))
        return -1;
        
    if (iter == lst->data[lst->head].prev)
        return ListPushBack(lst, x);
    
    ListInsert_Internal(lst, x, lst->data[iter].next);
    return lst->data[iter].next;
}
References List::data, List::head, isIteratorValid(), LIST_OK, ListInsert_Internal(), ListPushBack(), ListVerify(), Node::next, and Node::prev.
ListInsertBefore()
List_Iterator ListInsertBefore (struct List * lst, List_El x, List_Iterator iter)
Insert element x before iterator.
Parameters
lst Pointer to list
x Element which need to insert
iter Iterator before which need to insert element
Returns
Iterator of new inserted element
Definition at line 643 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    if (!isIteratorValid(lst, iter))
        return -1;
    
    lst->boost_mode = 0;
    
    if (iter == lst->head)
        return ListPushFront(lst, x);
    
    ListInsert_Internal(lst, x, iter);
    return lst->data[iter].prev;
}
References List::boost_mode, List::data, List::head, isIteratorValid(), LIST_OK, ListInsert_Internal(), ListPushFront(), ListVerify(), and Node::prev.
ListPopBack()
List_error ListPopBack (struct List * lst)
Erase element in the end of the list
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 492 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->size == 0)
        return LIST_ERROR;
    
    return ListErase_Internal(lst, lst->data[lst->head].prev);
}
References List::data, List::head, LIST_ERROR, LIST_OK, ListErase_Internal(), ListVerify(), Node::prev, and List::size.
Referenced by ListErase().
ListPopFront()
List_error ListPopFront (struct List * lst)
Erase element in front of the list
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 505 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->size == 0)
        return LIST_ERROR;
    
    if (lst->boost_mode == 1) lst->boost_mode = 0;
    
    return ListErase_Internal(lst, lst->head);
}
References List::boost_mode, List::head, LIST_ERROR, LIST_OK, ListErase_Internal(), ListVerify(), and List::size.
Referenced by ListErase().
ListPushBack()
List_Iterator ListPushBack (struct List * lst, List_El x)
Insert element in the end of the list
Parameters
lst Pointer to list
x Element which need to insert in the end
Returns
Iterator of the element x in list
Definition at line 444 of file list.c.
{
    assert(lst != NULL);
        
    if (ListVerify(lst) != LIST_OK)
        return -1;
            
    if (lst->size > 0)
    {
        if (ListInsert_Internal(lst, x, lst->head) == LIST_OK)
            return lst->data[lst->head].prev;
        else
            return -1;
    }
    else
    {
        if (ListInsert_Internal(lst, x, 0) == LIST_OK)
            return lst->head;
        else
            return -1;
    }
}
References List::data, List::head, LIST_OK, ListInsert_Internal(), ListVerify(), Node::prev, and List::size.
Referenced by ListInsertAfter().
ListPushFront()
List_Iterator ListPushFront (struct List * lst, List_El x)
Insert element in the begin of the list
Parameters
lst Pointer to list
x Element which need to insert in the begin
Returns
Iterator of the element x in list
Definition at line 467 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    List_error check = LIST_OK;
    if (lst->boost_mode == 1) lst->boost_mode = 0;
    
    if (lst->size > 0)
        check = ListInsert_Internal(lst, x, lst->head);
    else
        check = ListInsert_Internal(lst, x, 0);
    
    if (check == LIST_OK)
    {
        lst->head = lst->data[lst->head].prev;
        return lst->head;
    }
    else
        return -1;
}
References List::boost_mode, List::data, List::head, LIST_OK, ListInsert_Internal(), ListVerify(), Node::prev, and List::size.
Referenced by ListInsertBefore().
ListResize()
static List_error ListResize (struct List * lst, size_t new_cap) [static]
Reallocation of list's data memory
Parameters
lst Object List which data will be reallocated
new_cap New capacity for objest lst
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 143 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
        
    if (new_cap < lst->size ||
       (lst->boost_mode == 0 && new_cap <= lst->capacity) ||
       (lst->boost_mode == 1 && new_cap < lst->size))
        return LIST_ERROR;
    
    struct Node *new_data = (struct Node *)realloc(lst->data, new_cap * sizeof(struct Node));
    
    if (new_data == NULL)
        return LIST_WRONG_REALLOC;
    
    lst->data = new_data;
    
    if (new_cap == lst->size)
    {
        lst->capacity = new_cap;
        return LIST_OK;
    }
    
    int last_free = lst->free;
    if (last_free == -1)
        lst->free = lst->capacity;
    else
    {
        while(lst->data[last_free].next != -1)
            last_free = lst->data[last_free].next;
        
        lst->data[last_free].next = lst->capacity;
    }
    for (int i = lst->capacity; i < new_cap - 1; i++)
    {
        struct Node free_node = {-1, -1, i + 1};
        lst->data[i] = free_node;
    }
    struct Node last_node = {-1, -1, -1};
    lst->data[new_cap - 1] = last_node;
        
    lst->capacity = new_cap;
    return LIST_OK;
}
References List::boost_mode, List::capacity, List::data, List::free, LIST_ERROR, LIST_OK, LIST_WRONG_REALLOC, ListVerify(), Node::next, and List::size.
Referenced by ListInsert_Internal(), and ListShrinkToFit().
ListShrinkToFit()
List_error ListShrinkToFit (struct List * lst)
Changes capacity to size. Works ONLY in boosted list
Parameters
lst Pointer to list
Returns
Code of verify. LIST_OK if list OK, or another code if there's error
Definition at line 431 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return LIST_ERROR;
    
    if (lst->boost_mode == 1)
        return ListResize(lst, lst->size);
    else
        return LIST_ERROR;
}
References List::boost_mode, LIST_ERROR, LIST_OK, ListResize(), ListVerify(), and List::size.
ListSize()
size_t ListSize (struct List * lst)
Check list's size
Parameters
lst Pointer to list
Returns
Size of the list
Definition at line 520 of file list.c.
{
    assert(lst != NULL);
    
    if (ListVerify(lst) != LIST_OK)
        return -1;
    
    return lst->size;
}
References LIST_OK, ListVerify(), and List::size.
ListVerify()
static List_error ListVerify (struct List * lst) [static]
TODO: documentation for IsertAfter and GetIterator
Verify function list
Parameters
lst Object List which need to verify
Returns
Code of verify. LIST_OK if list OK, or another error if list bad
Definition at line 57 of file list.c.
{
    if (lst->data == NULL)
    {
        printf("Ban because lst-data == NULL\n");
        return LIST_ERROR;
    }
    if (lst->size > lst->capacity)
    {
        printf("Ban because of overflow\n");
        return LIST_OVERFLOW;
    }
    if (lst->size < 0)
    {
        printf("Ban because of underflow\n");
        return LIST_UNDERFLOW;
    }
    
    #ifdef DEBUG_MODE
    if (lst->head != -1)
    {
        int curr_node = lst->data[lst->head].next;
        int logic_number = 1;
        while (curr_node != lst->head && logic_number < lst->size)
        {
            curr_node = lst->data[curr_node].next;
            logic_number++;
        }
        if (logic_number != lst->size)
        {
            printf("There's cycle in upstream way\n");
            ListDump(lst);
            return LIST_CYCLE;
        }
        curr_node = lst->data[lst->head].prev;
        logic_number = 1;
        while (curr_node != lst->head && logic_number < lst->size)
        {
            curr_node = lst->data[curr_node].prev;
            logic_number++;
        }
        if (logic_number != lst->size)
        {
            printf("There's cycle in reverse way\n");
            ListDump(lst);
            return LIST_CYCLE;
        }
    }
    if (lst->free != -1)
    {
        int curr_node = lst->free;
        int logic_number = 0;
        while (curr_node != -1 && logic_number < lst->capacity - lst->size)
        {
            curr_node = lst->data[curr_node].next;
            logic_number++;
        }
        if (logic_number != lst->capacity - lst->size)
        {
            printf("There's cycle in free places\n");
            ListDump(lst);
            return LIST_CYCLE;
        }
    }
    #endif
    
    return LIST_OK;
}
References List::capacity, List::data, List::free, List::head, LIST_CYCLE, LIST_ERROR, LIST_OK, LIST_OVERFLOW, LIST_UNDERFLOW, ListDump(), Node::next, Node::prev, and List::size.
Referenced by GetIterator(), GetIterator_Value(), isIteratorValid(), isListBoosted(), IteratorDecrease(), IteratorIncrease(), ListBegin(), ListBoost(), ListConstruct(), ListDestruct(), ListEnd(), ListErase(), ListErase_Internal(), ListGetValue(), ListInsert_Internal(), ListInsertAfter(), ListInsertBefore(), ListPopBack(), ListPopFront(), ListPushBack(), ListPushFront(), ListResize(), ListShrinkToFit(), and ListSize().